
;understanding logical operations
;
; ANA <register>
; Logically ands the content of register with A
;
; Different than the hardwired and operation, 
; which accepts 2 input bits and gives 1 output
; bit.
; It works like 8 hardwired and gates, ands the
; bits of accumulator with corresponding bits of
; register hence resulting into 8 bit data whose
; each bit is generated by a single hrdwired and
; operation.
;
;	1000 0001
;	|||| ||||
;	1001 0101
;	---------
;	1000 0001
;
; resets the C flag and sets the AC

jmp start

;data


;code
start:	MVI A,01h
	MVI B,02h

	;1-byte instruction
	ANA B
	OUT 01h

hlt